blog/urls.py
from django.urls import path
from .views import (
    PostListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView,
    UserPostListView,
)
from . import views

urlpatterns = [
    path('', PostListView.as_view(), name='blog-home'),
    path('post/<slug:slug>', views.posts_by_tag, name='tag-posts'),
    path('post/<int:pk>/', views.post_detail, name='post-detail'),
    path('post/<int:pk>/like/', views.like_post, name='like-post'),
    path('post/new/', PostCreateView.as_view(), name='post-create'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('about/', views.about, name='blog-about'),
    path('user/<str:username>', UserPostListView.as_view(), name='user-posts'),
    path('rollback/', views.rollback_view, name='rollback'),
    path('resttest/', views.PostList.as_view()),
]

'''
как должна работать и быть реализована функция отката изменений - применение всех измененний ДО даты которую передали в функцию
связывающие таблицы
роли - через auth group
'''

dj_pr/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('add-moder/', user_views.add_new_moder, name='add-moder'),
    path('', include('blog.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
import uuid


class Tag(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField()
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField(max_length=100, unique=True)
    content = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag, blank=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post-detail', kwargs={'pk': self.pk})

    @property
    def reviewers(self):
        queryset = self.comments.all().values_list('author__id', flat=True)
        return queryset


class Comment(models.Model):
    content = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return self.content


class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)


class Temporary(models.Model):
    StartDate = models.DateTimeField(auto_now_add=True)
    EndDate = models.DateTimeField(null=True, blank=True)
    JsonData = models.JSONField()
    action = models.CharField(max_length=20, null=True)

    class Meta:
        indexes = [
            models.Index(fields=['StartDate']),
            models.Index(fields=['EndDate']),
        ]

blog/forms.py
from django.forms import ModelForm
from django import forms
from .models import Comment
from datetimepicker.widgets import DateTimePicker


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        labels = {
            'content': 'Добавьте комментарий'
        }

    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'input'})


class RollbackDataForm(forms.Form):
    date = forms.DateTimeField(widget=forms.DateTimeInput(attrs={'type': 'datetime-local'}))

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Post, Tag, Comment, Like
from django.contrib.auth.models import User
from .forms import CommentForm, RollbackDataForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .utils import rollback_to
from rest_framework import generics
from .serializers import PostSerializer


class PostList(generics.ListCreateAPIView):
    queryset = Post.objects.all()
    serializer_class = PostSerializer


def home(request):
    context = {
        'posts': Post.objects.all()
    }
    return render(request, 'blog/home.html', context)


class PostListView(ListView):
    model = Post
    template_name = 'blog/home.html'
    context_object_name = 'posts'
    ordering = ['-date_posted']
    paginate_by = 5


def post_detail(request, pk):
    post = Post.objects.get(pk=pk)
    tags = post.tags.all()
    form = CommentForm()

    if request.method == 'POST':
        form = CommentForm(request.POST)
        comment = form.save(commit=False)
        comment.post = post
        comment.author = request.user
        comment.save()
        messages.success(request, 'Ваш комментарий был добавлен!')
        return redirect('post-detail', pk=post.pk)
    return render(request, 'blog/post_detail.html', {"post": post, 'form': form})


@login_required
def rollback_view(request):
    form = RollbackDataForm()
    if request.method == 'POST':
        form = RollbackDataForm(request.POST)
        if form.is_valid():
            date = form.cleaned_data['date']
            rollback_to(date)
            messages.success(request, 'ура')
            return redirect('blog-home')
    return render(request, 'blog/rollback.html', {'form': form})


class PostDetailView(DetailView):
    model = Post


def posts_by_tag(request, slug):
    tag = get_object_or_404(Tag, slug=slug)
    posts = Post.objects.filter(tags__in=[tag])
    context = {
        'posts': posts,
        'tag': tag,
    }

    return render(request, 'blog/tag_posts.html', context)


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'content', 'tags']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    fields = ['title', 'content', 'tags']

    def form_valid(self, form):
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author or self.request.user.groups.get().name == 'Moderator':
            return True
        return False


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = '/'

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author or self.request.user.groups.get().name == 'Moderator':
            return True
        return False


def about(request):
    return render(request, 'blog/about.html', {'title': 'О клубе freakesss'})


class UserPostListView(ListView):
    model = Post
    template_name = 'blog/user_posts.html'
    context_object_name = 'posts'
    paginate_by = 5

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return Post.objects.filter(author=user).order_by('-date_posted')


@login_required
def like_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    like, created = Like.objects.get_or_create(user=request.user, post=post)

    if not created:
        like.delete()

    return redirect('post-detail', pk=post.pk)


# тут сделать обработчик чтоб принять запрос и вызвать из утилс

'''
комментарии
лайки/дизлайки
пользователи
посты
разделы
тэги
темпоральная таблица
'''

blog/templates/blog/about.html
{% extends "blog/base.html" %}
{% block content %}
    <h1>Клуб Python Bytes</h1>
{% endblock content %}

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

    <!-- Обязательные мета-теги -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap, иконки и шрифт -->
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
     <link href='http://fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,400italic,500,500italic,700,700italic,900italic,900' rel='stylesheet' type='text/css'>
     <link rel="stylesheet" type="text/css" href="{% static 'blog/main.css' %}">
     <link href='https://unpkg.com/boxicons@2.1.2/css/boxicons.min.css' rel='stylesheet'>

    {% if title %}
        <title>Блог клуба {{ title }}</title>
    {% else %}
        <title>Блог клуба FS1010</title>
    {% endif %}
</head>
<body>
 <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-blue fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="{% url 'blog-home' %}"><i class='bx bxs-rocket bx-tada-hover'></i>FS 1010</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link " href="{% url 'blog-home' %}">Главная</a>
              <a class="nav-item nav-link" href="{% url 'blog-about' %}">О клубе</a>
            </div>
            <!-- Правая часть навигационной панели -->
            <div class="navbar-nav">
              {% if user.is_authenticated %}
                {% if user.groups.get.name == 'Moderator' %}
                    <a class="nav-item nav-link" href="{% url 'add-moder' %}">Добавить модератора</a>
                {% endif %}
                <a class="nav-item nav-link" href="{% url 'post-create' %}">Новый пост</a>
            	<a class="nav-item nav-link" href="{% url 'profile' %}">Профиль</a>
            	<a class="nav-item nav-link" href="{% url 'logout' %}">Выход</a>
          	{% else %}
            	<a class="nav-item nav-link" href="{% url 'login' %}">Вход</a>
            	<a class="nav-item nav-link" href="{% url 'register' %}">Регистрация</a>
          	{% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
          {% block content %}{% endblock %}
        </div>
        <div class="col-md-4">
          <div class="content-section">
            <h3>Разделы</h3>
            <p class='text-muted'>новости и события
              <ul class="list-group">
              {% if user.is_staff %}
                <a class="list-group-item list-group-item-light" href="{% url 'rollback' %}">Откат изменений</a>
              {% endif %}
              </ul>
            </p>
          </div>
        </div>
      </div>

    </main>
    <!-- Футер закреплен внизу, независимо от количества постов на странице -->
    <footer class="text-center bg-dark">
      <p><a href="{% url 'blog-home' %}">© FS1010 2022</a></p>
    </footer>

</body>
</html>

blog/templates/blog/home.html
{% extends "blog/base.html" %}
{% block content %}
    {% for post in posts %}
        <article class="media content-section">
            <a href="{% url 'user-posts' post.author.username %}">
                <img class="rounded-circle article-img" src="{{ post.author.profile.image.url }}">
            </a>
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{% url 'user-posts' post.author.username %}">{{ post.author }}</a>
              <small class="text-muted">{{ post.date_posted|date:"F d, Y" }}</small>
            </div>
            <h2><a class="article-title" href="{% url 'post-detail' post.id %}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
                    <div>
      {% if post.tags.all %}
        {% for tag in post.tags.all %}
              <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'tag-posts' tag.slug %}">{{tag}}</a>
        {% endfor %}
      {% endif %}

        </div>
          </div>

        </article>
    {% endfor %}
    <div class="pagination justify-content-center">
    {% if is_paginated %}

      {% if page_obj.has_previous %}

        <a class="btn btn-outline-info mb-4 mr-1" href="?page=1">Первая</a>
        <a class="btn btn-outline-info mb-4 mr-1" href="?page={{ page_obj.previous_page_number }}">Предыдущая</a>
      {% endif %}

      {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
          <a class="btn btn-info mb-4 mr-1" href="?page={{ num }}">{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
          <a class="btn btn-outline-info mb-4 mr-1" href="?page={{ num }}">{{ num }}</a>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <a class="btn btn-outline-info mb-4 mr-1" href="?page={{ page_obj.next_page_number }}">Следующая</a>
        <a class="btn btn-outline-info mb-4 mr-1" href="?page={{ page_obj.paginator.num_pages }}">Последняя</a>
      {% endif %}

    {% endif %}
  </div>
{% endblock content %}

blog/templates/blog/post_confirm_delete.html
{% extends "blog/base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Удаление записи</legend>
                <h2>Вы уверены, что хотите удалить запись "{{ object.title }}" ?</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Да, хочу удалить</button>
                <a class="btn btn-outline-secondary" href="{% url 'post-detail' object.id %}">Отмена</a>
            </div>
        </form>
    </div>
{% endblock content %}

blog/templates/blog/post_detail.html
{% extends "blog/base.html" %}
{% block content %}
{% load static %}
<article class="media content-section">
    <img class="rounded-circle article-img" src="{{ post.author.profile.image.url }}">
    <div class="media-body">
      <div class="article-metadata">
        <a class="mr-2" href="{% url 'user-posts' post.author.username %}">{{ post.author }}</a>
        <small class="text-muted">{{ post.date_posted|date:"F d, Y" }}</small>
        {% if post.author == user or user.groups.get.name == 'Moderator'%}
          <div>
            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'post-update' post.id %}">Редактировать</a>
            <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'post-delete' post.id %}">Удалить</a>
          </div>
        {% endif %}
      </div>
      <h2 class="article-title">{{ post.title }}</h2>
      <p class="article-content">{{ post.content }}</p>
      <div>
      {% if post.tags.all %}
        {% for tag in post.tags.all %}
              <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'tag-posts' tag.slug %}">{{tag}}</a>
        {% endfor %}
      {% endif %}
    <div class="like">

          <a href="{% url 'like-post' post.pk %}">
              <div class="heart"></div>
          </a>
              <div class="count">
                  {{ post.like_set.all.count }}
              </div>

    </div>
        </div>
    </div>
  </article>
    <div class="media-body">
      <h2 class="article-title">Комментарии</h2>

      <div class="comments">
                {% for comment in post.comment_set.all %}
          {% if comment.content %}
          <article class="media content-section">

            <a href="{% url 'user-posts' comment.author %}">
                <img class="rounded-circle article-img" src="{{ comment.author.profile.image.url }}" alt="user" />
            </a>
            <div>
                <div class="comment">
                    <div class="comment__details">
                        <a href="{% url 'user-posts' comment.author %}"
                            class="mr-2">{{ comment.author }}</a>
                        <small class="text-muted">{{ comment.created|date:"F d, Y" }}</small>
                    </div>
                    <p class="comment__info">{{ comment.content|linebreaksbr }}</p>
                </div>
            </div>
          </article>
                {% endif %}
                {% endfor %}
                    {% if request.user.is_authenticated %}
                    <form class="form" action="{% url 'post-detail' post.id %}" method="POST">
                        {% csrf_token %}
                        {% for field in form %}
                        <div class="form__field">
                            <label for="formInput#textarea">{{ field.label }}</label>
                            {{field}}
                        </div>
                        {% endfor %}
                        <input class="btn btn--sub btn--lg" type="submit" value="Готово" />
                    </form>
                    {% else %}
                    <a href="{% url 'login' %}?next={{ request.path }}">Войдите, чтобы оставить отзыв</a>
                    {% endif %}
                </div>
    </div>
{% endblock content %}

blog/templates/blog/post_form.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Новая запись</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Сохранить</button>
            </div>
        </form>
    </div>
{% endblock content %}

blog/templates/blog/rollback.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Сохранить</button>
            </div>
        </form>
    </div>
{% endblock content %}

blog/templates/blog/tag_posts.html
{% extends "blog/base.html" %}
{% block content %}
    <h1 class="mb-3">Посты с тэгом {{ tag }}</h1>
    {% for post in posts %}
        <article class="media content-section">
          <img class="rounded-circle article-img" src="{{ post.author.profile.image.url }}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{% url 'user-posts' post.author.username %}">{{ object.author }}</a>
              <small class="text-muted">{{ post.date_posted|date:"F d, Y" }}</small>
            </div>
            <h2><a class="article-title" href="{% url 'post-detail' post.id %}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
              <div>
                        {% if post.tags.all %}
        {% for tag in post.tags.all %}
              <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'tag-posts' tag.slug %}">{{tag}}</a>
        {% endfor %}
      {% endif %}
              </div>
          </div>
        </article>
    {% endfor %}
    <div class="pagination justify-content-center">
    {% if is_paginated %}

      {% if page_obj.has_previous %}
        <a class="btn btn-outline-info mb-4 mr-1" href="?page=1">Первая</a>
        <a class="btn btn-outline-info mb-4 mr-1" href="?page={{ page_obj.previous_page_number }}">Предыдущая</a>
      {% endif %}

      {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
          <a class="btn btn-info mb-4 mr-1" href="?page={{ num }}">{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
          <a class="btn btn-outline-info mb-4 mr-1" href="?page={{ num }}">{{ num }}</a>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <a class="btn btn-outline-info mb-4 mr-1" href="?page={{ page_obj.next_page_number }}">Следующая</a>
        <a class="btn btn-outline-info mb-4 mr-1" href="?page={{ page_obj.paginator.num_pages }}">Последняя</a>
      {% endif %}

    {% endif %}
  </div>
{% endblock content %}

blog/templates/blog/user_posts.html
{% extends "blog/base.html" %}
{% block content %}
    <h1 class="mb-3">Записи пользователя {{ view.kwargs.username }} ({{ page_obj.paginator.count }})</h1>
    {% for post in posts %}
        <article class="media content-section">
          <img class="rounded-circle article-img" src="{{ post.author.profile.image.url }}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{% url 'user-posts' post.author.username %}">{{ object.author }}</a>
              <small class="text-muted">{{ post.date_posted|date:"F d, Y" }}</small>
            </div>
            <h2><a class="article-title" href="{% url 'post-detail' post.id %}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
              <div>
                        {% if post.tags.all %}
        {% for tag in post.tags.all %}
              <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'tag-posts' tag.slug %}">{{tag}}</a>
        {% endfor %}
      {% endif %}
              </div>
          </div>
        </article>
    {% endfor %}
    <div class="pagination justify-content-center">
    {% if is_paginated %}

      {% if page_obj.has_previous %}
        <a class="btn btn-outline-info mb-4 mr-1" href="?page=1">Первая</a>
        <a class="btn btn-outline-info mb-4 mr-1" href="?page={{ page_obj.previous_page_number }}">Предыдущая</a>
      {% endif %}

      {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
          <a class="btn btn-info mb-4 mr-1" href="?page={{ num }}">{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
          <a class="btn btn-outline-info mb-4 mr-1" href="?page={{ num }}">{{ num }}</a>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <a class="btn btn-outline-info mb-4 mr-1" href="?page={{ page_obj.next_page_number }}">Следующая</a>
        <a class="btn btn-outline-info mb-4 mr-1" href="?page={{ page_obj.paginator.num_pages }}">Последняя</a>
      {% endif %}

    {% endif %}
  </div>
{% endblock content %}